#===========================================================================
# CONFIGURACION CONTEXTO
#===========================================================================
server:
  port: ${SERVER_PORT:8081}

#===========================================================================
# EUREKA
#===========================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka

#===========================================================================
# LOGGING
#===========================================================================
log:
  path:${LOG_PATH}
  
#===========================================================================
# GATEWAY
#===========================================================================
spring:
  cloud:
    gateway:
      routes:
      - id: ms-customers
        uri: lb://MS-CUSTOMERS
        predicates:
          - Path=/customers/**
      - id: ms-bank-accounts
        uri: lb://MS-BANK-ACCOUNTS
        predicates:
          - Path=/bank-accounts/**
      - id: ms-bank-account-balance-management
        uri: lb://MS-BANK-ACCOUNT-BALANCE-MANAGEMENT
        predicates:
          - Path=/bank-account-balance/**
      - id: ms-credits
        uri: lb://MS-CREDITS
        predicates:
          - Path=/credits/**
      - id: ms-customers-products-overview
        uri: lb://MS-CUSTOMERS-PRODUCTS-OVERVIEW
        predicates:
          - Path=/customers-products-overview/**
      - id: ms-wallet-holder
        uri: lb://MS-WALLET-HOLDER
        predicates:
          - Path=/wallet-holders/**       
      - id: ms-wallet-transactions
        uri: lb://MS-WALLET-TRANSACTIONS
        predicates:
          - Path=/wallet-transactions/**           
      - id: ms-wallet-yanki
        uri: lb://MS-WALLET-YANKI
        predicates:
          - Path=/wallet-yanki/**               
