#===========================================================================
# CONFIGURACION CONTEXTO
#===========================================================================
server:
  port: ${SERVER_PORT:8081}

#===========================================================================
# EUREKA
#===========================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka

#===========================================================================
# LOGGING
#===========================================================================
log:
  path:${LOG_PATH}
  
#===========================================================================
# GATEWAY
#===========================================================================
spring:
  cloud:
    gateway:
      routes:
      - id: ms-customers
        uri: lb://mscustomers
        predicates:
          - Path=/customers/**
      - id: ms-bank-accounts
        uri: lb://msbankaccount
        predicates:
          - Path=/bank-accounts/**
      - id: ms-credits
        uri: lb://mscredits
        predicates:
          - Path=/credits/**
      - id: ms-customers-products-overview
        uri: lb://mscustomersproductsoverview
        predicates:
          - Path=/customers-products-overview/**           
